image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./s01_init_workspace.sh
  - command: ./s02_local_run.sh
ports: 
  - port: 5000
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
  - port: 8100
    onOpen: open-preview
  - port: 8101
    onOpen: open-preview
  - port: 8102
    onOpen: open-preview
  - port: 8103
    onOpen: open-preview
