service: codelog-webtemplate-20200928

frameworkVersion: ">=2.3.0 <3.0.0"

provider:
  name: aws
  runtime: python3.7

functions:
  endpoint:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: endpoint.app
    pythonBin: python
  pythonRequirements:
    dockerizePip: false
  customDomain:
    domainName: ${file(../conf/conf.json):DOMAIN}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
